[package]
name = "shapes"
version = "0.1.0"
authors = ["Thomas J. Kennedy <tkennedy@cs.odu.edu>"]
edition = "2024"

[dependencies]
ordered-float = "1.0.2"
itertools = "0.8"
eyre = "0.6.12"

[dev-dependencies]
hamcrest2 = "*"
stringreader = "0.1.1"
